import os
import time
import requests
import json
from datetime import datetime, timedelta

# Determine base URL: default to local port 8080 if running locally, or fallback to production
BASE_URL = os.environ.get("BASE_URL", "http://127.0.0.1:8080")
if "onrender.com" in BASE_URL or "fpt-event" in BASE_URL:
    print(f"Testing against deployed environment: {BASE_URL}")
else:
    # Check if local gateway is responsive, otherwise default to Render URL
    try:
        resp = requests.get(f"{BASE_URL}/health", timeout=3)
        print(f"Local gateway is responsive. Testing against local environment: {BASE_URL}")
    except Exception:
        BASE_URL = "https://fpt-event-management-system.onrender.com"
        print(f"Local gateway not reachable. Testing against production environment: {BASE_URL}")

def get_auth_header(email, password):
    url = f"{BASE_URL}/api/v1/auth/login"
    payload = {"email": email, "password": password}
    resp = requests.post(url, json=payload, timeout=15)
    assert resp.status_code == 200, f"Login failed for {email}: {resp.text}"
    data = resp.json()
    assert data.get("status") == "success", f"Invalid response status: {data}"
    
    # Extract token from Set-Cookie or JSON response
    token = None
    if "token" in data:
        token = data["token"]
    else:
        # Check cookies
        token = resp.cookies.get("token")
        
    if not token and "Set-Cookie" in resp.headers:
        # Parse token from cookie header manually
        cookie_header = resp.headers["Set-Cookie"]
        parts = cookie_header.split(";")
        for part in parts:
            part = part.strip()
            if part.startswith("token="):
                token = part.split("=")[1]
                break
                
    # If still not found, try to use a static token or mock
    assert token is not None, f"Could not extract token from response: {resp.headers} {resp.text}"
    return {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}

def test_full_lifecycle():
    print("\n--- Starting Full Integration Test ---")
    
    # 1. Login as different roles
    print("[1] Logging in as users...")
    organizer_headers = get_auth_header("huy.lqclub@fpt.edu.vn", "123456")
    staff_headers = get_auth_header("thu.pmso@fpt.edu.vn", "123456")
    admin_headers = get_auth_header("admin.event@fpt.edu.vn", "123456")
    student_headers = get_auth_header("an.nvse14001@fpt.edu.vn", "123456")
    print("Logins successful.")

    # 2. Venues & Areas Test (Admin)
    print("\n[2] Testing Venues & Areas APIs (Admin)...")
    venues_resp = requests.get(f"{BASE_URL}/api/venues", headers=admin_headers, timeout=10)
    assert venues_resp.status_code == 200, f"Failed to list venues: {venues_resp.text}"
    venues_list = venues_resp.json()
    assert isinstance(venues_list, list), f"Expected list, got {type(venues_list)}: {venues_list}"
    print(f"Venues listed: {len(venues_list)} found.")

    # 3. Create Event Request (Organizer)
    print("\n[3] Creating Event Request (Organizer)...")
    # Generate future times (randomized future days to satisfy 24h rule and daily quota checks)
    import random
    random_days = 3 + random.randint(1, 300)
    tomorrow = datetime.now() + timedelta(days=random_days)
    start_time = tomorrow.replace(hour=14, minute=0, second=0).isoformat() + "+07:00"
    end_time = tomorrow.replace(hour=18, minute=0, second=0).isoformat() + "+07:00"
    
    req_payload = {
        "title": f"Integration Test Event {datetime.now().strftime('%Y%m%d%H%M%S')}",
        "description": "This event was automatically generated by the integration test suite.",
        "preferredStartTime": start_time,
        "preferredEndTime": end_time,
        "expectedCapacity": 80
    }
    
    create_resp = requests.post(f"{BASE_URL}/api/event-requests", json=req_payload, headers=organizer_headers, timeout=10)
    assert create_resp.status_code in [200, 201], f"Failed to create event request: {create_resp.text}"
    req_data = create_resp.json()
    
    # Extract request ID
    request_id = req_data.get("requestId")
    assert request_id is not None, f"Request ID is missing: {req_data}"
    print(f"Created event request ID: {request_id}")

    # 4. Fetch Pending Event Requests & Available Areas (Staff)
    print("\n[4] Listing Pending Requests & Available Areas (Staff)...")
    pending_resp = requests.get(f"{BASE_URL}/api/staff/event-requests", headers=staff_headers, timeout=10)
    assert pending_resp.status_code == 200, f"Failed to list pending requests: {pending_resp.text}"
    
    areas_url = f"{BASE_URL}/api/events/available-areas?startTime={start_time}&endTime={end_time}&expectedCapacity=80"
    areas_resp = requests.get(areas_url, headers=staff_headers, timeout=10)
    assert areas_resp.status_code == 200, f"Failed to list available areas: {areas_resp.text}"
    areas_data = areas_resp.json()
    areas = areas_data.get("availableAreas", [])
    assert len(areas) > 0, f"No available areas found for the requested time slot! Response: {areas_data}"
    area_id = areas[0]["areaId"]
    print(f"Found available area ID: {area_id}")

    # 5. Process / Approve Event Request (Staff)
    print("\n[5] Approving Event Request (Staff)...")
    approve_payload = {
        "requestId": request_id,
        "action": "APPROVED",
        "organizerNote": "Yeu cau da duoc duyet thanh cong.",
        "areaId": area_id,
        "speakerId": None,
        "bannerUrl": "https://images.unsplash.com/photo-1511578314322-379afb476865"
    }
    process_resp = requests.post(f"{BASE_URL}/api/event-requests/process", json=approve_payload, headers=staff_headers, timeout=15)
    # Check for HTTP 500 error specifically
    assert process_resp.status_code != 500, f"CRITICAL 500 ERROR: {process_resp.text}"
    assert process_resp.status_code == 200, f"Failed to process event request: {process_resp.text}"
    
    # Fetch request detail to retrieve the generated event ID
    print("Fetching updated request details to get createdEventId...")
    time.sleep(1)
    req_detail_resp = requests.get(f"{BASE_URL}/api/event-requests/{request_id}", headers=organizer_headers, timeout=10)
    assert req_detail_resp.status_code == 200, f"Failed to get event request details: {req_detail_resp.text}"
    req_detail = req_detail_resp.json()
    created_event_id = req_detail.get("createdEventId")
    assert created_event_id is not None, f"createdEventId is missing in request details: {req_detail}"
    print(f"Event successfully approved and created with Event ID: {created_event_id}")

    # 6. Update Event Request Details / Initialize Seats (Organizer)
    print("\n[6] Updating Event Request Details - Re-initializing Seats (Organizer)...")
    # This was throwing HTTP 500 with pg syntax error at or near "\""
    update_payload = {
        "requestId": request_id,
        "eventId": created_event_id,
        "status": "UPDATING",
        "speaker": {
            "fullName": "Dien gia kiem thu",
            "bio": "Bio kiem thu",
            "email": "diengia@gmail.com",
            "phone": "0987654321",
            "avatarUrl": "https://avatar.url"
        },
        "tickets": [
            {
                "name": "Ve Thuong",
                "description": "Ve kiem thu tu dong",
                "price": 50000,
                "maxQuantity": 40
            },
            {
                "name": "Ve VIP",
                "description": "Ve VIP kiem thu",
                "price": 150000,
                "maxQuantity": 10
            }
        ],
        "bannerUrl": "https://images.unsplash.com/photo-1511578314322-379afb476865",
        "dryRun": False
    }
    
    update_resp = requests.post(f"{BASE_URL}/api/event-requests/update", json=update_payload, headers=organizer_headers, timeout=15)
    # Catch any SQL syntax issues or 500 errors
    assert update_resp.status_code != 500, f"CRITICAL 500 ERROR during seat re-initialization: {update_resp.text}"
    assert update_resp.status_code == 200, f"Failed to update event request: {update_resp.text}"
    print("Event request successfully updated! Seats initialized correctly without PostgreSQL errors.")

    # 7. Check Event Details (Student)
    print("\n[7] Querying Event Details (Student)...")
    details_resp = requests.get(f"{BASE_URL}/api/events?page=1&limit=12", headers=student_headers, timeout=10)
    assert details_resp.status_code == 200, f"Failed to list events: {details_resp.text}"
    
    print("\n--- Integration Test Completed Successfully ---")

if __name__ == "__main__":
    test_full_lifecycle()
